### ISSUE TITLE
Error if timestamp is specified too large

### ISSUE THREAD

**Issue by phil-davis** [swalladge/rpi-temperature-server#25]
e.g. specify some wacky huge number as the timestamp:
api/temperature/99999999999999999999999999999999

and the server code falls over in database.py get_temperature_at() when trying to do the query for the temperature record nearest the timestamp. The underlying SQL engine can't cope with more than a 64-bit integer.

It needs some try/except handling there to return a 400 "invalid timestamp" rather than bombing out.

**Comment by swalladge** [comment]
Ouch. Yep I can add an additional check to the validation function.
Thanks.

**Comment by swalladge** [comment]
Fixed. :)
