### ISSUE TITLE
Web app needs to know it has test data

### ISSUE THREAD

**Issue by phil-davis** [swalladge/rpi-temperature-server#46]
When running with test data, we currently have on_rpi=false and the web app says:
"Server is in test mode generating random temperature data"
It would be nice if the web app could find out that the server is using test data, and so say something more accurate. It needs the "info" endpoint to have extra added to it.

**Comment by swalladge** [comment]
Isn't this the behaviour wanted anyway? If it's not in 'live' mode (ie. with `on_rpi=True` in the config), then it must be test data.

**Comment by phil-davis** [comment]
Well, it could be "random" data or actual fixed test data read from file.

**Comment by swalladge** [comment]
Either way it's in 'test' mode - perhaps the webapp message just needs to drop the part about random data being generated and simply say it's in test mode or that the data isn't real.

**Comment by phil-davis** [comment]
Done.
