### ISSUE TITLE
Web App min or max does not display if at end point of graph

### ISSUE THREAD

**Issue by phil-davis** [swalladge/rpi-temperature-server#60]
In the web app, if I select a time period where the minimum or maximum temperature occurs at the very beginning or end of the period, then the minimum or maximum is not shown in the graph.
![temperaturesensorgraphnomaxmin](https://cloud.githubusercontent.com/assets/1535615/19227392/ef36de1e-8ef7-11e6-97c2-8e0cce4f582e.png)

**Comment by swalladge** [comment]
That may be a limitation of the graphing library.

Might find info at the homepage: http://metricsgraphicsjs.org/

**Comment by phil-davis** [comment]
Yes, I suspect so. After a quick look I don't see anything obviously dodgy with our code.

**Comment by phil-davis** [comment]
Upstream issue https://github.com/mozilla/metrics-graphics/issues/719
Upstream suggested fix https://github.com/mozilla/metrics-graphics/pull/720
